# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
driver = webdriver.Chrome()
# Test name: editar
# Step # | name | target | value
# 1 | open | https://qa.dyalogo.cloud/manager/modulo/usuarios | 
driver.get("https://qa.dyalogo.cloud/manager/modulo/usuarios")
# 2 | setWindowSize | 1386x739 | 
driver.set_window_size(1386, 739)

  # 3 | type | name=txtUsuario | santicri163@gmail.com
driver.find_element(By.NAME, "txtUsuario").send_keys("santicri163@gmail.com")
    # 4 | type | name=txtPassword | MqwoOP19
driver.find_element(By.NAME, "txtPassword").send_keys("MqwoOP190")
    # 5 | click | name=txtUsuario | 
driver.find_element(By.NAME, "txtUsuario").click()
driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()
    # 6 | type | name=txtUsuario | senadyalogo@gmail.coms
driver.find_element(By.NAME, "txtUsuario").send_keys("santicri163@gmail.com")
    # 7 | type | name=txtPassword | 123456789
driver.find_element(By.NAME, "txtPassword").send_keys("JaaeGyfF")
    # 8 | click | css=.col-xs-4 > .btn | 
driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()


    # 9 | click | css=.select2-container--below .select2-selection__arrow | 
time.sleep(3)
driver.get("https://qa.dyalogo.cloud/manager/modulo/usuarios")
# 3 | click | id=table_search_lista_navegacion | 
driver.find_element(By.ID, "table_search_lista_navegacion").click()
# 4 | type | id=table_search_lista_navegacion | sena
driver.find_element(By.ID, "table_search_lista_navegacion").send_keys("sena")
# 5 | sendKeys | id=table_search_lista_navegacion | ${KEY_ENTER}
driver.find_element(By.ID, "table_search_lista_navegacion").send_keys(Keys.ENTER)
# 6 | click | id=table_search_lista_navegacion | 
driver.find_element(By.ID, "table_search_lista_navegacion").click()
# 7 | type | id=table_search_lista_navegacion | sena
# 9 | click | id=edit | 
driver.find_element(By.ID, "edit").click()
# 10 | click | id=NombreUsuario | 
# 12 | click | id=IdentificacionUsuario | 
driver.find_element(By.ID, "IdentificacionUsuario").click()
# 13 | click | id=NombreUsuario | 
driver.find_element(By.ID, "NombreUsuario").click()
# 14 | type | id=NombreUsuario | Usuario Sena Dyalogo 
driver.find_element(By.ID, "NombreUsuario").clear()
driver.find_element(By.ID, "NombreUsuario").send_keys("usuario")
driver.find_element(By.ID, "NombreUsuario").clear()
driver.find_element(By.ID, "NombreUsuario").send_keys("Usuario Sena Dyalogo Todo")
# 15 | click | id=IdentificacionUsuario | 
driver.find_element(By.ID, "IdentificacionUsuario").click()
driver.find_element(By.ID, "IdentificacionUsuario").clear()


# 16 | type | id=IdentificacionUsuario | 101465675
driver.find_element(By.ID, "IdentificacionUsuario").send_keys("101465675")
# 17 | click | id=Correo | 
driver.find_element(By.ID, "Correo").click()
# 18 | click | id=IdentificacionUsuario | 
driver.find_element(By.ID, "IdentificacionUsuario").click()
# 19 | type | id=IdentificacionUsuario | 1014656757

driver.find_element(By.ID, "IdentificacionUsuario").clear()
driver.find_element(By.ID, "IdentificacionUsuario").send_keys("1014656757")
# 20 | click | id=Correo | 
driver.find_element(By.ID, "Correo").click()
# 21 | click | css=.col-md-9 > .row:nth-child(2) | 
driver.find_element(By.CSS_SELECTOR, ".col-md-9 > .row:nth-child(2)").click()
# 22 | click | id=Correo | 
driver.find_element(By.ID, "Correo").click()
# 23 | click | id=Correo | 
driver.find_element(By.ID, "Correo").click()
# 24 | click | id=estadoUsuario | 
driver.find_element(By.ID, "estadoUsuario").click()
# 25 | select | id=estadoUsuario | label=Inactivo
dropdown = driver.find_element(By.ID, "estadoUsuario")
dropdown.find_element(By.XPATH, "//option[. = 'Inactivo']").click()
# 26 | click | css=.col-md-9:nth-child(1) | 
driver.find_element(By.CSS_SELECTOR, ".col-md-9:nth-child(1)").click()
# 27 | click | id=Correo | 
driver.find_element(By.ID, "Correo").click()
# 28 | type | id=Correo | 1
driver.find_element(By.ID, "Correo").clear()

# 29 | type | id=Correo | senadyalogo@gmail.com
driver.find_element(By.ID, "Correo").send_keys("senadyalogo@gmail.com")
# 30 | click | id=estadoUsuario | 
driver.find_element(By.ID, "estadoUsuario").click()
# 31 | select | id=estadoUsuario | label=Activo
dropdown = driver.find_element(By.ID, "estadoUsuario")
dropdown.find_element(By.XPATH, "//option[. = 'Activo']").click()
# 32 | click | id=Cargo | 
driver.find_element(By.ID, "Cargo").click()
# 33 | select | id=Cargo | label=Administrador Avanzado
dropdown = driver.find_element(By.ID, "Cargo")
dropdown.find_element(By.XPATH, "//option[. = 'Administrador Avanzado']").click()
# 34 | click | id=Cargo | 
driver.find_element(By.ID, "Cargo").click()
# 35 | select | id=Cargo | label=Administrador
dropdown = driver.find_element(By.ID, "Cargo")
dropdown.find_element(By.XPATH, "//option[. = 'Administrador']").click()
# 36 | click | css=.fa-save | 
driver.find_element(By.CSS_SELECTOR, ".fa-save").click()
