# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Chrome()
# Test name: CP06.1
# Step # | name | target | value
# 1 | open | https://qa.dyalogo.cloud/manager/modulo/usuarios | 
driver.get("https://qa.dyalogo.cloud/manager/modulo/usuarios")
# 2 | setWindowSize | 1004x708 | 
driver.set_window_size(1382, 736)
# 22 | click | name=txtUsuario | 
driver.find_element(By.NAME, "txtUsuario").click()
# 23 | type | name=txtUsuario | pluisanys@gmail.com
driver.find_element(By.NAME, "txtUsuario").send_keys("pluisanys@gmail.com")
# 24 | click | name=txtPassword | 
driver.find_element(By.NAME, "txtPassword").click()
# 25 | click | css=.iCheck-helper | 
driver.find_element(By.CSS_SELECTOR, ".iCheck-helper").click()
# 26 | type | name=txtPassword | ZVG14qxy
driver.find_element(By.NAME, "txtPassword").send_keys("ZVG14qxy")
# 27 | click | css=.col-xs-4 > .btn | 
driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()
time.sleep(3)
# 3 | click | css=#add > .fa | 
driver.get("https://qa.dyalogo.cloud/manager/modulo/usuarios")
driver.find_element(By.CSS_SELECTOR, "#add > .fa").click()
# 4 | click | id=NombreUsuario | 
driver.find_element(By.ID, "NombreUsuario").click()
# 5 | type | id=NombreUsuario | Maritza Mariana Valentina
driver.find_element(By.ID, "NombreUsuario").send_keys("Maritza Mariana Valentina")
# 6 | click | id=Correo | 
driver.find_element(By.ID, "Correo").click()
# 7 | type | id=Correo | valentinamarinamaritza@gmail.com
driver.find_element(By.ID, "Correo").send_keys("valentinamarinamaritza@gmail.com")
# 8 | click | id=IdentificacionUsuario | 
driver.find_element(By.ID, "IdentificacionUsuario").click()
# 9 | type | id=IdentificacionUsuario | 1364798512
driver.find_element(By.ID, "IdentificacionUsuario").send_keys("1364798512")
# 10 | click | id=Cargo | 
driver.find_element(By.ID, "Cargo").click()
# 11 | select | id=Cargo | label=Agente
dropdown = driver.find_element(By.ID, "Cargo")
dropdown.find_element(By.XPATH, "//option[. = 'Agente']").click()
# 12 | click | css=.fa-save | 
driver.find_element(By.CSS_SELECTOR, ".fa-save").click()
time.sleep(3)
# 13 | click | id=table_search_lista_navegacion | 
driver.find_element(By.ID, "table_search_lista_navegacion").click()
# 14 | type | id=table_search_lista_navegacion | marit
driver.find_element(By.ID, "table_search_lista_navegacion").send_keys("marit")
# 15 | sendKeys | id=table_search_lista_navegacion | ${KEY_ENTER}
driver.find_element(By.ID, "table_search_lista_navegacion").send_keys(Keys.ENTER)
# 16 | type | id=table_search_lista_navegacion | marit
driver.find_element(By.ID, "table_search_lista_navegacion").send_keys("marit")
# 17 | sendKeys | id=table_search_lista_navegacion | ${KEY_ENTER}
driver.find_element(By.ID, "table_search_lista_navegacion").send_keys(Keys.ENTER)
time.sleep(5)
# 18 | click | css=td > p:nth-child(2) | 
# 19 | click | css=#delete > .fa | 
driver.find_element(By.CSS_SELECTOR, "#delete > .fa").click()
# 20 | click | id=alertify-ok | 
time.sleep(3)
driver.find_element(By.ID, "alertify-ok").click()

driver.quit()