# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
driver = webdriver.Chrome()
 # Test name: Activo_Inactivo
 # Step # | name | target | value
 # 1 | open | https://qa.dyalogo.cloud/manager/modulo/usuarios | 
driver.get("https://qa.dyalogo.cloud")
 # 2 | setWindowSize | 1936x1056 | 
 driver.set_window_size(1936, 1056)
 # 3 | click | id=edit | 
 driver.find_element(By.NAME, "txtUsuario").click()
# 23 | type | name=txtUsuario | pluisanys@gmail.com
driver.find_element(By.NAME, "txtUsuario").send_keys("pluisanys@gmail.com")
# 24 | click | name=txtPassword | 
driver.find_element(By.NAME, "txtPassword").click()
# 25 | click | css=.iCheck-helper | 
driver.find_element(By.CSS_SELECTOR, ".iCheck-helper").click()
# 26 | type | name=txtPassword | ZVG14qxy
driver.find_element(By.NAME, "txtPassword").send_keys("ZVG14qxy")
# 27 | click | css=.col-xs-4 > .btn | 
driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()
time.sleep(3)
 driver.find_element(By.ID, "edit").click()
 # 4 | click | id=estadoUsuario | 
 driver.find_element(By.ID, "estadoUsuario").click()
 # 5 | select | id=estadoUsuario | label=Inactivo
 dropdown = driver.find_element(By.ID, "estadoUsuario")
 dropdown.find_element(By.XPATH, "//option[. = 'Inactivo']").click()
 # 6 | click | id=estadoUsuario | 
 driver.find_element(By.ID, "estadoUsuario").click()
 # 7 | select | id=estadoUsuario | label=Activo
 dropdown = driver.find_element(By.ID, "estadoUsuario")
 dropdown.find_element(By.XPATH, "//option[. = 'Activo']").click()
