# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Chrome()
driver.get("https://qa.dyalogo.cloud/manager/login.php")
driver.set_window_size(1382, 736)
# Test name: inicio de secion qa
# Step # | name | target | value
# 1 | open | https://qa.dyalogo.cloud/ | 
driver.get("https://qa.dyalogo.cloud/")
# 2 | setWindowSize | 1318x692 | 
driver.set_window_size(1318, 692)
# 3 | click | linkText=SUPERVISIÓN | 
driver.find_element(By.LINK_TEXT, "SUPERVISIÓN").click()
# 4 | type | name=txtUsuario | santicri163@gmail.com
driver.find_element(By.NAME, "txtUsuario").send_keys("santicri163@gmail.com")
# 5 | type | name=txtPassword | O6cUZkel
driver.find_element(By.NAME, "txtPassword").send_keys("O6cUZkel")
# 6 | click | name=txtUsuario | 
driver.find_element(By.NAME, "txtUsuario").click()
# 7 | click | name=txtPassword | 
driver.find_element(By.NAME, "txtPassword").click()
# 8 | click | name=txtUsuario | 
driver.find_element(By.NAME, "txtUsuario").click()
# 9 | type | name=txtUsuario | senadyalogos@gmail.com
driver.find_element(By.NAME, "txtUsuario").send_keys("senadyalogos@gmail.com")
# 10 | click | name=txtPassword | 
driver.find_element(By.NAME, "txtPassword").click()
# 11 | type | name=txtPassword | 1234567890
driver.find_element(By.NAME, "txtPassword").send_keys("1234567890")
# 12 | click | css=.col-xs-4 > .btn | 
driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()
# 13 | type | name=txtUsuario | pluisanys@gmail.com
driver.find_element(By.NAME, "txtUsuario").send_keys("pluisanys@gmail.com")
# 14 | type | name=txtPassword | O6cUZkel
driver.find_element(By.NAME, "txtPassword").send_keys("O6cUZkel")
# 15 | click | css=.iCheck-helper | 
driver.find_element(By.CSS_SELECTOR, ".iCheck-helper").click()
# 16 | click | css=.iCheck-helper | 
driver.find_element(By.CSS_SELECTOR, ".iCheck-helper").click()
# 17 | click | id=recordarPass | 
driver.find_element(By.ID, "recordarPass").click()
# 18 | click | id=txtMail | 
driver.find_element(By.ID, "txtMail").click()
# 19 | type | id=txtMail | mesadeayuda7@dyalogo.com
driver.find_element(By.ID, "txtMail").send_keys("mesadeayuda7@dyalogo.com")
# 20 | click | id=btnEnviarPass | 
driver.find_element(By.ID, "btnEnviarPass").click()
# 21 | click | id=loginVolver | 
driver.find_element(By.ID, "loginVolver").click()
# 22 | click | name=txtUsuario | 
driver.find_element(By.NAME, "txtUsuario").click()
# 23 | type | name=txtUsuario | pluisanys@gmail.com
driver.find_element(By.NAME, "txtUsuario").send_keys("pluisanys@gmail.com")
# 24 | click | name=txtPassword | 
driver.find_element(By.NAME, "txtPassword").click()
# 25 | click | css=.iCheck-helper | 
driver.find_element(By.CSS_SELECTOR, ".iCheck-helper").click()
# 26 | type | name=txtPassword | ZVG14qxy
driver.find_element(By.NAME, "txtPassword").send_keys("ZVG14qxy")
# 27 | click | css=.col-xs-4 > .btn | 
driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()
