# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


driver = webdriver.Chrome()
driver.get("https://qa.dyalogo.cloud/manager/login")
driver.set_window_size(1382, 736)
    # Test name: CP02
    # Step # | name | target | value
    # 1 | open | https://bpo-2.dyalogo.cloud/manager/index.php?page=TiempoReal | 
driver.get("https://bpo-2.dyalogo.cloud/manager/index.php?page=TiempoReal")
# 2 | setWindowSize | 1382x744 | 
driver.set_window_size(1382, 744)
# 3 | click | css=.fa-sitemap | 
driver.find_element(By.CSS_SELECTOR, ".fa-sitemap").click()
# 4 | click | css=td > p:nth-child(2) | 
driver.find_element(By.CSS_SELECTOR, "td > p:nth-child(2)").click()
# 5 | click | id=edit | 
driver.find_element(By.ID, "edit").click()
# 6 | click | css=.ion | 
driver.find_element(By.CSS_SELECTOR, ".ion").click()
# 7 | click | css=#myDiagramDiv > canvas | 
driver.find_element(By.CSS_SELECTOR, "#myDiagramDiv > canvas").click()
# 8 | click | css=#myDiagramDiv > canvas | 
driver.find_element(By.CSS_SELECTOR, "#myDiagramDiv > canvas").click()
# 9 | doubleClick | xpath=//div[@id='myDiagramDiv']/canvas | 
element = driver.find_element(By.XPATH, "//div[@id=\'myDiagramDiv\']/canvas")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 10 | runScript | window.scrollTo(0,0) | 
driver.execute_script("window.scrollTo(0,0)")
