# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
driver = webdriver.Chrome()
# Test name: Crear Formulario
# Step # | name | target | value
# 1 | open | https://qa.dyalogo.cloud/manager/modulo/guion/73dc7ba1230f53df37ed3b07e5d22464 | 
driver.get("https://qa.dyalogo.cloud/manager/modulo/guion/73dc7ba1230f53df37ed3b07e5d22464")
# 2 | setWindowSize | 1382x736 | 
driver.set_window_size(1382, 736)

  # 3 | type | name=txtUsuario | santicri163@gmail.com
driver.find_element(By.NAME, "txtUsuario").send_keys("santicri163@gmail.com")
    # 4 | type | name=txtPassword | MqwoOP19
driver.find_element(By.NAME, "txtPassword").send_keys("MqwoOP190")
    # 5 | click | name=txtUsuario | 
driver.find_element(By.NAME, "txtUsuario").click()
driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()
    # 6 | type | name=txtUsuario | senadyalogo@gmail.coms
driver.find_element(By.NAME, "txtUsuario").send_keys("santicri163@gmail.com")
    # 7 | type | name=txtPassword | 123456789
driver.find_element(By.NAME, "txtPassword").send_keys("JaaeGyfF")
    # 8 | click | css=.col-xs-4 > .btn | 
driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()


    # 9 | click | css=.select2-container--below .select2-selection__arrow | 
time.sleep(3)
driver.get("https://qa.dyalogo.cloud/manager/modulo/guion/73dc7ba1230f53df37ed3b07e5d22464")
# 3 | click | css=#add > .fa | 
driver.find_element(By.CSS_SELECTOR, "#add > .fa").click()
time.sleep(2)
# 4 | click | id=txtNombreGuion | 
driver.find_element(By.ID, "txtNombreGuion").click()
# 5 | type | id=txtNombreGuion | Formulario prueba SKids
driver.find_element(By.ID, "txtNombreGuion").send_keys("Formulario prueba SKids")
# 6 | click | id=guardarNewGuion | 
driver.find_element(By.ID, "guardarNewGuion").click()
# 7 | click | linkText=Secciones y campos (Máximo 30 campos por sección) | 
driver.find_element(By.LINK_TEXT, "Secciones y campos (Máximo 30 campos por sección)").click()
time.sleep(3)
# 8 | click | css=#seccion_10219 .btn-primary > .fa | 

try:
    Select = driver.find_element(By.XPATH, '//*[@id="seccion_11495"]/div/div/button[1]')

    Select.click()
    
except:
    Select = driver.find_element(By.XPATH, '/html/body/div[7]/div[2]/section[2]/div/div[2]/div/div[2]/div[2]/form/div/div/div[2]/div[2]/div/div/div[1]/div/div/button[1]')
    Select.click()

#driver.find_element(By.ID, '//*[@id="seccion_11495"]/div/div/button[1]').click()
# 9 | click | id=EditarG7_C33 |
time.sleep(2) 
driver.find_element(By.ID, "EditarG7_C33").click()
# 10 | type | id=EditarG7_C33 | Formulario SK
driver.find_element(By.ID, "EditarG7_C33").send_keys("Formulario SK")
# 11 | click | id=EditarG7_C35 | 
driver.find_element(By.ID, "EditarG7_C35").click()
# 12 | click | id=EditarG7_C38 | 
driver.find_element(By.ID, "EditarG7_C38").click()
# 13 | click | id=EditarG7_C38 | 
driver.find_element(By.ID, "EditarG7_C38").click()
# 14 | click | id=EditarG7_C36 | 
driver.find_element(By.ID, "EditarG7_C36").click()
# 15 | select | id=EditarG7_C36 | label=Normal
dropdown = driver.find_element(By.ID, "EditarG7_C36")
time.sleep(2)

try:
    Select = driver.find_element(By.XPATH, '//*[@id="EditarG7_C36"]')

    Select.click()
    
    Option= driver.find_element(By.XPATH,'//*[@id="EditarG7_C36"]/option[3]' )
    Option.click()
except:
    Select = driver.find_element(By.XPATH, '/html/body/div[7]/div[8]/div/div/div[2]/form/div[1]/div[1]/div[4]/select')
    Select.click()

    Option= driver.find_element(By.XPATH,'/html/body/div[7]/div[8]/div/div/div[2]/form/div[1]/div[1]/div[4]/select/option[3]')
    Option.click()
#select.find_element(By.XPATH, "//option[. = 'Normal']").click()
# 16 | click | id=EditarG7_C36 | 
driver.find_element(By.ID, "EditarG7_C36").click()
# 17 | select | id=EditarG7_C36 | label=Solo titulo
time.sleep(2)
dropdown = driver.find_element(By.ID, "EditarG7_C36")
time.sleep(2)
dropdown.find_element(By.XPATH, "//option[. = 'Solo titulo']").click()
# 18 | click | id=EditarG7_C36 | 
driver.find_element(By.ID, "EditarG7_C36").click()
# 19 | select | id=EditarG7_C36 | label=Titulo y borde
dropdown = driver.find_element(By.ID, "EditarG7_C36")
dropdown.find_element(By.XPATH, "//option[. = 'Titulo y borde']").click()
# 20 | click | id=EditarG7_C36 | 
driver.find_element(By.ID, "EditarG7_C36").click()
# 21 | select | id=EditarG7_C36 | label=Pestaña
dropdown = driver.find_element(By.ID, "EditarG7_C36")
dropdown.find_element(By.XPATH, "//option[. = 'Pestaña']").click()
# 22 | click | id=EditarG7_C36 | 
driver.find_element(By.ID, "EditarG7_C36").click()
# 23 | select | id=EditarG7_C36 | label=Acordeon
dropdown = driver.find_element(By.ID, "EditarG7_C36")
dropdown.find_element(By.XPATH, "//option[. = 'Acordeon']").click()
# 24 | click | id=EditarG7_C37 | 
driver.find_element(By.ID, "EditarG7_C37").click()
# 25 | click | id=EditarG7_C37 | 
driver.find_element(By.ID, "EditarG7_C37").click()
# 26 | click | id=newFieldSeccion2 | 
driver.find_element(By.ID, "newFieldSeccion2").click()
# 27 | mouseOver | id=newFieldSeccion2 | 
element = driver.find_element(By.ID, "newFieldSeccion2")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
# 28 | mouseOut | id=newFieldSeccion2 | 
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element, 0, 0).perform()
# 29 | click | id=G6_C39_1 | 
driver.find_element(By.ID, "G6_C39_1").click()
# 30 | type | id=G6_C39_1 | Nombre
driver.find_element(By.ID, "G6_C39_1").send_keys("Nombre")
# 31 | click | id=newFieldSeccion2 | 
driver.find_element(By.ID, "newFieldSeccion2").click()
# 32 | click | id=G6_C39_2 | 
driver.find_element(By.ID, "G6_C39_2").click()
# 33 | type | id=G6_C39_2 | Apellido
driver.find_element(By.ID, "G6_C39_2").send_keys("Apellido")
# 34 | click | id=newFieldSeccion2 | 
driver.find_element(By.ID, "newFieldSeccion2").click()
# 35 | click | id=G6_C39_3 | 
driver.find_element(By.ID, "G6_C39_3").click()
# 36 | type | id=G6_C39_3 | Segundo Apellido
driver.find_element(By.ID, "G6_C39_3").send_keys("Segundo Apellido")
# 37 | click | id=newFieldSeccion2 | 
driver.find_element(By.ID, "newFieldSeccion2").click()
# 38 | click | id=G6_C39_4 | 
driver.find_element(By.ID, "G6_C39_4").click()
# 39 | type | id=G6_C39_4 | Tipo de identificacion
driver.find_element(By.ID, "G6_C39_4").send_keys("Tipo de identificacion")
# 40 | click | id=newFieldSeccion2 | 
driver.find_element(By.ID, "newFieldSeccion2").click()
# 41 | click | id=G6_C39_5 | 
driver.find_element(By.ID, "G6_C39_5").click()
# 42 | type | id=G6_C39_5 | Numero de identificacion
driver.find_element(By.ID, "G6_C39_5").send_keys("Numero de identificacion")
# 43 | click | id=newFieldSeccion2 | 
driver.find_element(By.ID, "newFieldSeccion2").click()
# 44 | click | id=G6_C39_6 | 
driver.find_element(By.ID, "G6_C39_6").click()
# 45 | type | id=G6_C39_6 | Correo
driver.find_element(By.ID, "G6_C39_6").send_keys("Correo")
# 46 | click | id=newFieldSeccion2 | 
driver.find_element(By.ID, "newFieldSeccion2").click()
# 47 | mouseOver | id=newFieldSeccion2 | 
element = driver.find_element(By.ID, "newFieldSeccion2")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
# 48 | mouseOut | id=newFieldSeccion2 | 
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element, 0, 0).perform()
# 49 | click | id=G6_C39_7 | 
driver.find_element(By.ID, "G6_C39_7").click()
# 50 | type | id=G6_C39_7 | Celular
driver.find_element(By.ID, "G6_C39_7").send_keys("Celular")
# 51 | click | id=newFieldSeccion2 | 
driver.find_element(By.ID, "newFieldSeccion2").click()
# 52 | mouseOver | id=newFieldSeccion2 | 
element = driver.find_element(By.ID, "newFieldSeccion2")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
# 53 | mouseOut | id=newFieldSeccion2 | 
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element, 0, 0).perform()
# 54 | click | id=G6_C39_8 | 
driver.find_element(By.ID, "G6_C39_8").click()
# 55 | type | id=G6_C39_8 | Direccion
driver.find_element(By.ID, "G6_C39_8").send_keys("Direccion")
# 56 | click | id=G6_C40_4 | 
driver.find_element(By.ID, "G6_C40_4").click()
# 57 | select | id=G6_C40_4 | label=Lista
dropdown = driver.find_element(By.ID, "G6_C40_4")
dropdown.find_element(By.XPATH, "//option[. = 'Lista']").click()
# 58 | click | id=nuevaListaModalH_4 | 
driver.find_element(By.ID, "nuevaListaModalH_4").click()
# 59 | mouseOver | id=nuevaListaModalH_4 | 
element = driver.find_element(By.ID, "nuevaListaModalH_4")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
# 60 | mouseOut | id=nuevaListaModalH_4 | 
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element, 0, 0).perform()
# 61 | click | id=txtNombreLista | 
driver.find_element(By.ID, "txtNombreLista").click()
# 62 | type | id=txtNombreLista | lista identificacion
driver.find_element(By.ID, "txtNombreLista").send_keys("lista identificacion")
# 63 | click | id=txtPreguntaPadre | 
driver.find_element(By.ID, "txtPreguntaPadre").click()
# 64 | click | id=txtPreguntaPadre | 
driver.find_element(By.ID, "txtPreguntaPadre").click()
# 65 | click | id=newOpcion | 
driver.find_element(By.ID, "newOpcion").click()
# 66 | mouseOver | id=newOpcion | 
element = driver.find_element(By.ID, "newOpcion")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
# 67 | mouseOut | id=newOpcion | 
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element, 0, 0).perform()
# 68 | click | name=opciones_0 | 
driver.find_element(By.NAME, "opciones_0").click()
# 69 | type | name=opciones_0 | NUIP (Numero unico de identificacion personal)
driver.find_element(By.NAME, "opciones_0").send_keys("NUIP (Numero unico de identificacion personal)")
# 70 | click | id=newOpcion | 
driver.find_element(By.ID, "newOpcion").click()
# 71 | mouseOver | id=newOpcion | 
element = driver.find_element(By.ID, "newOpcion")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
# 72 | mouseOut | id=newOpcion | 
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element, 0, 0).perform()
# 73 | click | name=opciones_1 | 
driver.find_element(By.NAME, "opciones_1").click()
# 74 | type | name=opciones_1 | CC (Cedula de Ciudadania)
driver.find_element(By.NAME, "opciones_1").send_keys("CC (Cedula de Ciudadania)")
# 75 | click | id=newOpcion | 
driver.find_element(By.ID, "newOpcion").click()
# 76 | mouseOver | id=newOpcion | 
element = driver.find_element(By.ID, "newOpcion")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
# 77 | mouseOut | id=newOpcion | 
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element, 0, 0).perform()
# 78 | click | name=opciones_2 | 
driver.find_element(By.NAME, "opciones_2").click()
# 79 | type | name=opciones_2 | CE (Cedula Extranjera)
driver.find_element(By.NAME, "opciones_2").send_keys("CE (Cedula Extranjera)")
# 80 | click | id=newOpcion | 
driver.find_element(By.ID, "newOpcion").click()
# 81 | click | name=opciones_3 | 
driver.find_element(By.NAME, "opciones_3").click()
# 82 | type | name=opciones_3 | Pasaporte
driver.find_element(By.NAME, "opciones_3").send_keys("Pasaporte")
# 83 | click | id=guardarLista | 
driver.find_element(By.ID, "guardarLista").click()
# 84 | click | id=G6_C40_6 | 
driver.find_element(By.ID, "G6_C40_6").click()
# 85 | select | id=G6_C40_6 | label=Email
dropdown = driver.find_element(By.ID, "G6_C40_6")
dropdown.find_element(By.XPATH, "//option[. = 'Email']").click()
# 86 | click | id=G6_C40_7 | 
driver.find_element(By.ID, "G6_C40_7").click()
# 87 | select | id=G6_C40_7 | label=Numerico
dropdown = driver.find_element(By.ID, "G6_C40_7")
dropdown.find_element(By.XPATH, "//option[. = 'Numerico']").click()
# 88 | click | id=G6_C40_8 | 
driver.find_element(By.ID, "G6_C40_8").click()
# 89 | click | id=editarSeccionesModalButton | 
driver.find_element(By.ID, "editarSeccionesModalButton").click()
# 90 | click | css=.fa-save | 
driver.find_element(By.CSS_SELECTOR, ".fa-save").click()
# 91 | click | id=table_search_lista_navegacion | 
driver.find_element(By.ID, "table_search_lista_navegacion").click()
# 92 | type | id=table_search_lista_navegacion | prueba skids
driver.find_element(By.ID, "table_search_lista_navegacion").send_keys("prueba skids")
# 93 | sendKeys | id=table_search_lista_navegacion | ${KEY_ENTER}
driver.find_element(By.ID, "table_search_lista_navegacion").send_keys(Keys.ENTER)
# 94 | click | css=td | 
driver.find_element(By.CSS_SELECTOR, "td").click()
# 95 | click | id=delete | 
driver.find_element(By.ID, "delete").click()
# 96 | mouseOver | id=delete | 
element = driver.find_element(By.ID, "delete")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
# 97 | mouseOut | id=delete | 
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element, 0, 0).perform()
# 98 | click | id=alertify-ok | 
driver.find_element(By.ID, "alertify-ok").click()
