# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestIniciodesecion():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_iniciodesecion(self):
    # Test name: inicio de secion
    # Step # | name | target | value
    # 1 | open | https://bpo-2.dyalogo.cloud/ | 
    self.driver.get("https://bpo-2.dyalogo.cloud/")
    # 2 | setWindowSize | 1004x708 | 
    self.driver.set_window_size(1004, 708)
    # 3 | click | linkText=SUPERVISIÓN | 
    self.driver.find_element(By.LINK_TEXT, "SUPERVISIÓN").click()
    # 4 | type | name=txtUsuario | santicri163@hotmail.com
    self.driver.find_element(By.NAME, "txtUsuario").send_keys("santicri163@hotmail.com")
    # 5 | type | name=txtPassword | DkDtsic
    self.driver.find_element(By.NAME, "txtPassword").send_keys("DkDtsic")
    # 6 | click | css=.col-xs-4 > .btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()
    # 7 | type | name=txtUsuario | santicri163@gmail.com
    self.driver.find_element(By.NAME, "txtUsuario").send_keys("santicri163@gmail.com")
    # 8 | type | name=txtPassword | DkDtsic
    self.driver.find_element(By.NAME, "txtPassword").send_keys("DkDtsic")
    # 9 | click | css=.col-xs-4 > .btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()
    # 10 | click | name=txtUsuario | 
    self.driver.find_element(By.NAME, "txtUsuario").click()
    # 11 | type | name=txtUsuario | senadyalogo@gmail.com
    self.driver.find_element(By.NAME, "txtUsuario").send_keys("senadyalogo@gmail.com")
    # 12 | click | name=txtPassword | 
    self.driver.find_element(By.NAME, "txtPassword").click()
    # 13 | type | name=txtPassword | 123456789
    self.driver.find_element(By.NAME, "txtPassword").send_keys("123456789")
    # 14 | click | css=.col-xs-4 > .btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()
    # 15 | click | css=.select2-container--below .select2-selection__arrow | 
    self.driver.find_element(By.CSS_SELECTOR, ".select2-container--below .select2-selection__arrow").click()
    # 16 | click | css=.select2-search__field | 
    self.driver.find_element(By.CSS_SELECTOR, ".select2-search__field").click()
    # 17 | type | css=.select2-search__field | sen
    self.driver.find_element(By.CSS_SELECTOR, ".select2-search__field").send_keys("sen")
    # 18 | sendKeys | css=.select2-search__field | ${KEY_ENTER}
    self.driver.find_element(By.CSS_SELECTOR, ".select2-search__field").send_keys(Keys.ENTER)
    # 19 | click | id=btnGuardar | 
    self.driver.find_element(By.ID, "btnGuardar").click()
  
