# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Chrome()
driver.get("https://qa.dyalogo.cloud/manager/login.php")
driver.set_window_size(1382, 736)
  
  

  

    # Test name: CP01
    # Step # | name | target | value
    # 1 | open | https://bpo-2.dyalogo.cloud/manager/login.php | 

    # 3 | type | name=txtUsuario | santicri163@gmail.com
driver.find_element(By.NAME, "txtUsuario").send_keys("santicri163@gmail.com")
    # 4 | type | name=txtPassword | MqwoOP19
driver.find_element(By.NAME, "txtPassword").send_keys("MqwoOP190")
    # 5 | click | name=txtUsuario | 
driver.find_element(By.NAME, "txtUsuario").click()
driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()
    # 6 | type | name=txtUsuario | senadyalogo@gmail.coms
driver.find_element(By.NAME, "txtUsuario").send_keys("santicri163@gmail.com")
    # 7 | type | name=txtPassword | 123456789
driver.find_element(By.NAME, "txtPassword").send_keys("JaaeGyfF")
    # 8 | click | css=.col-xs-4 > .btn | 
driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()


    # 9 | click | css=.select2-container--below .select2-selection__arrow | 
time.sleep(3)
    # Test name: HOLA
    # Step # | name | target | value
    # 1 | open | /manager/modulo/estrategias | 
driver.get("https://qa.dyalogo.cloud/manager/modulo/estrategias")
 

driver.find_element(By.ID, "table_search_lista_navegacion").click()
# 4 | type | id=table_search_lista_navegacion | sena
driver.find_element(By.ID, "table_search_lista_navegacion").send_keys("sena")
# 5 | sendKeys | id=table_search_lista_navegacion | ${KEY_ENTER}
driver.find_element(By.ID, "table_search_lista_navegacion").send_keys(Keys.ENTER)
# 6 | click | id=table_search_lista_navegacion | 
driver.find_element(By.ID, "table_search_lista_navegacion").click()
 # 2 | setWindowSize | 1382x744 | 
 # 3 | click | css=.fa-edit | 
driver.find_element(By.CSS_SELECTOR, ".fa-edit").click()
 # 4 | click | css=.wrapper |#driver.find_element(By.CSS_SELECTOR, ".wrapper").click() # 5 | type | id=G2_C7 |  sena
driver.find_element(By.ID, "G2_C7").click()
driver.find_element(By.ID, "G2_C7").clear() 
 # 6 | click | css=#s_resumen_estrategia > .box-body > .row:nth-child(1) | 
driver.find_element(By.CSS_SELECTOR, "#s_resumen_estrategia > .box-body > .row:nth-child(1)").click()
 # 7 | click | id=G2_C7 | 
driver.find_element(By.ID, "G2_C7").click()
 # 8 | type | id=G2_C7 | SENA
driver.find_element(By.ID, "G2_C7").send_keys("sena kids")
 # 9 | click | css=#s_resumen_estrategia > .box-body > .row:nth-child(1) | 
driver.find_element(By.CSS_SELECTOR, "#s_resumen_estrategia > .box-body > .row:nth-child(1)").click()
 # 10 | click | id=G2_C6 | 
driver.find_element(By.ID, "G2_C6").click()
 # 11 | select | id=G2_C6 | label=Campaña entrante simple
dropdown =driver.find_element(By.ID, "G2_C6")
dropdown.find_element(By.XPATH, "//option[. = 'Campaña entrante simple']").click()
 # 12 | click | css=.input-group-addon | 
driver.find_element(By.CSS_SELECTOR, ".input-group-addon").click()
 # 13 | click | css=.colorpicker | 
driver.find_element(By.CSS_SELECTOR, ".colorpicker").click()
 # 14 | click | css=.colorpicker | 
driver.find_element(By.CSS_SELECTOR, ".colorpicker").click()
 # 15 | click | id=G2_C8 | 
driver.find_element(By.ID, "G2_C8").click()
 # 16 | click | id=G2_C8 | 
driver.find_element(By.ID, "G2_C8").clear()
 # 17 | type | id=G2_C8 | Prueba
driver.find_element(By.ID, "G2_C8").send_keys("Prueba")
 # 18 | click | css=.col-md-12 > .panel:nth-child(1) > .box-header | 
driver.find_element(By.CSS_SELECTOR, ".col-md-12 > .panel:nth-child(1) > .box-header").click()
 # 19 | click | css=.fa-save | 
driver.find_element(By.CSS_SELECTOR, ".fa-save").click()
 # 20 | click | css=.fa-edit | 
driver.find_element(By.CSS_SELECTOR, ".fa-edit").click()
 # 21 | click | css=.box > .box-body > .row | 
driver.find_element(By.CSS_SELECTOR, ".box > .box-body > .row").click()
 # 22 | click | css=.box > .box-body > .row | 
driver.find_element(By.CSS_SELECTOR, ".box > .box-body > .row").click()
 # 23 | type | id=G2_C7 | sena
driver.find_element(By.ID, "G2_C7").send_keys("")
 # 24 | click | id=Save | 
driver.find_element(By.ID, "Save").click()
time.sleep(3)
driver.quit()