# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHOLA():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_hOLA(self):
    # Test name: HOLA
    # Step # | name | target | value
    # 1 | open | /manager/modulo/estrategias | 
    self.driver.get("https://bpo-2.dyalogo.cloud/manager/modulo/estrategias")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1382, 744)
    # 3 | click | css=.fa-edit | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa-edit").click()
    # 4 | click | css=.wrapper | 
    self.driver.find_element(By.CSS_SELECTOR, ".wrapper").click()
    # 5 | type | id=G2_C7 |  sena
    self.driver.find_element(By.ID, "G2_C7").send_keys(" sena")
    # 6 | click | css=#s_resumen_estrategia > .box-body > .row:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, "#s_resumen_estrategia > .box-body > .row:nth-child(1)").click()
    # 7 | click | id=G2_C7 | 
    self.driver.find_element(By.ID, "G2_C7").click()
    # 8 | type | id=G2_C7 | SENA
    self.driver.find_element(By.ID, "G2_C7").send_keys("SENA")
    # 9 | click | css=#s_resumen_estrategia > .box-body > .row:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, "#s_resumen_estrategia > .box-body > .row:nth-child(1)").click()
    # 10 | click | id=G2_C6 | 
    self.driver.find_element(By.ID, "G2_C6").click()
    # 11 | select | id=G2_C6 | label=Campaña entrante simple
    dropdown = self.driver.find_element(By.ID, "G2_C6")
    dropdown.find_element(By.XPATH, "//option[. = 'Campaña entrante simple']").click()
    # 12 | click | css=.input-group-addon | 
    self.driver.find_element(By.CSS_SELECTOR, ".input-group-addon").click()
    # 13 | click | css=.colorpicker | 
    self.driver.find_element(By.CSS_SELECTOR, ".colorpicker").click()
    # 14 | click | css=.colorpicker | 
    self.driver.find_element(By.CSS_SELECTOR, ".colorpicker").click()
    # 15 | click | id=G2_C8 | 
    self.driver.find_element(By.ID, "G2_C8").click()
    # 16 | click | id=G2_C8 | 
    self.driver.find_element(By.ID, "G2_C8").click()
    # 17 | type | id=G2_C8 | Prueba
    self.driver.find_element(By.ID, "G2_C8").send_keys("Prueba")
    # 18 | click | css=.col-md-12 > .panel:nth-child(1) > .box-header | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-12 > .panel:nth-child(1) > .box-header").click()
    # 19 | click | css=.fa-save | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa-save").click()
    # 20 | click | css=.fa-edit | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa-edit").click()
    # 21 | click | css=.box > .box-body > .row | 
    self.driver.find_element(By.CSS_SELECTOR, ".box > .box-body > .row").click()
    # 22 | click | css=.box > .box-body > .row | 
    self.driver.find_element(By.CSS_SELECTOR, ".box > .box-body > .row").click()
    # 23 | type | id=G2_C7 | sena
    self.driver.find_element(By.ID, "G2_C7").send_keys("sena")
    # 24 | click | id=Save | 
    self.driver.find_element(By.ID, "Save").click()
    # 25 | mouseOver | id=Save | 
    element = self.driver.find_element(By.ID, "Save")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 26 | mouseOut | id=Save | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 27 | click | css=.fa-edit | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa-edit").click()
    # 28 | click | id=G2_C7 | 
    self.driver.find_element(By.ID, "G2_C7").click()
    # 29 | type | id=G2_C7 | SENA
    self.driver.find_element(By.ID, "G2_C7").send_keys("SENA")
    # 30 | click | css=.box > .box-body > .row | 
    self.driver.find_element(By.CSS_SELECTOR, ".box > .box-body > .row").click()
    # 31 | type | id=G2_C7 | PRUEBA SENA
    self.driver.find_element(By.ID, "G2_C7").send_keys("PRUEBA SENA")
    # 32 | click | id=Save | 
    self.driver.find_element(By.ID, "Save").click()
    # 33 | mouseOver | id=Save | 
    element = self.driver.find_element(By.ID, "Save")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 34 | mouseOut | id=Save | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
