# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCP02():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cP02(self):
    self.driver.get("https://qa.dyalogo.cloud/manager/modulo/estrategias")
    self.driver.set_window_size(1382, 744)
    self.driver.find_element(By.CSS_SELECTOR, ".fa-sitemap").click()
    self.driver.find_element(By.ID, "table_search_lista_navegacion").click()
    self.driver.find_element(By.ID, "table_search_lista_navegacion").send_keys("laura")
    self.driver.find_element(By.ID, "table_search_lista_navegacion").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "#\\32 b036f4892dad21d0dedf3ecd5c94270 > td").click()
    self.driver.find_element(By.ID, "txtPruebas").click()
    self.driver.find_element(By.CSS_SELECTOR, "td > p:nth-child(2)").click()
    self.driver.find_element(By.ID, "edit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ion").click()
    self.driver.find_element(By.CSS_SELECTOR, "#myDiagramDiv > canvas").click()
    self.driver.find_element(By.CSS_SELECTOR, "#myDiagramDiv > canvas").click()
    element = self.driver.find_element(By.XPATH, "//div[@id=\'myDiagramDiv\']/canvas")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
  
