# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

driver = webdriver.Chrome()
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | https://bpo-2.dyalogo.cloud/manager/login | 
driver.get("https://bpo-2.dyalogo.cloud/manager/login")
# 2 | setWindowSize | 1382x744 | 
driver.set_window_size(1382, 744)
# 3 | click | css=.col-xs-4 > .btn | 

# Obtener el tamaño de la pantalla
screen_width = driver.execute_script("return window.screen.width;")
screen_height = driver.execute_script("return window.screen.height;")

# Establecer el tamaño de la ventana del navegador
driver.set_window_size(screen_width, screen_height)

# Busca el campo de nombre de usuario
name = driver.find_element("xpath", '//*[@id="Login"]/div[2]/form/div[1]/input')
name.send_keys("senadyalogo@gmail.com")

# Busca el campo de contraseña
password = driver.find_element("xpath", '//*[@id="Login"]/div[2]/form/div[2]/input')
password.send_keys("123456789")

# Hace clic en el botón de inicio de sesión
driver.find_element("xpath", '//*[@id="Login"]/div[2]/form/div[3]/div[2]/button').click()

# Espera 2 segundos
time.sleep(2)
# 6 | click | id=select2-cmbHuesped-container | 
driver.find_element(By.ID, "select2-cmbHuesped-container").click()
# 7 | click | id=select2-cmbHuesped-container | 
driver.find_element(By.ID, "select2-cmbHuesped-container").click()
# 8 | doubleClick | id=select2-cmbHuesped-container | 
element = driver.find_element(By.ID, "select2-cmbHuesped-container")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 9 | click | id=select2-cmbHuesped-container | 
driver.find_element(By.ID, "select2-cmbHuesped-container").click()
# 10 | click | id=select2-cmbHuesped-container | 
driver.find_element(By.ID, "select2-cmbHuesped-container").click()
# 11 | doubleClick | id=select2-cmbHuesped-container | 
element = driver.find_element(By.ID, "select2-cmbHuesped-container")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 12 | click | id=select2-cmbHuesped-container | 
driver.find_element(By.ID, "select2-cmbHuesped-container").click()
# 13 | click | css=.select2-search | 
driver.find_element(By.CSS_SELECTOR, ".select2-search").click()
# 14 | click | css=.select2-search__field | 
driver.find_element(By.CSS_SELECTOR, ".select2-search__field").click()
# 15 | click | id=PonerHuesped | 
driver.find_element(By.ID, "PonerHuesped").click()
# 16 | doubleClick | id=PonerHuesped | 
element = driver.find_element(By.ID, "PonerHuesped")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 17 | click | id=btnGuardar | 
driver.find_element(By.ID, "btnGuardar").click()
# 18 | click | linkText=Estrategias | 
driver.find_element(By.LINK_TEXT, "Estrategias").click()
# 19 | click | css=#dd597ac9e24ff9390b2dde2e80f3cf8e p:nth-child(1) | 
driver.find_element(By.CSS_SELECTOR, "#dd597ac9e24ff9390b2dde2e80f3cf8e p:nth-child(1)").click()
# 20 | click | css=.blockOverlay | 
driver.find_element(By.CSS_SELECTOR, ".blockOverlay").click()
# 21 | doubleClick | css=.blockOverlay | 
element = driver.find_element(By.CSS_SELECTOR, ".blockOverlay")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 22 | click | id=edit | 
driver.find_element(By.ID, "edit").click()
# 23 | click | css=.info-box-icon | 
driver.find_element(By.CSS_SELECTOR, ".info-box-icon").click()
# 24 | click | css=#myDiagramDiv > canvas | 
driver.find_element(By.CSS_SELECTOR, "#myDiagramDiv > canvas").click()
# 25 | click | css=#myDiagramDiv > canvas | 
driver.find_element(By.CSS_SELECTOR, "#myDiagramDiv > canvas").click()
# 26 | doubleClick | css=#myDiagramDiv > canvas | 
element = driver.find_element(By.CSS_SELECTOR, "#myDiagramDiv > canvas")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 27 | runScript | window.scrollTo(0,0) | 
driver.execute_script("window.scrollTo(0,0)")
# 28 | click | linkText=ADMINISTRAR REGISTROS | 
driver.find_element(By.LINK_TEXT, "ADMINISTRAR REGISTROS").click()
# 29 | doubleClick | linkText=ADMINISTRAR REGISTROS | 
element = driver.find_element(By.LINK_TEXT, "ADMINISTRAR REGISTROS")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 30 | click | id=abrir_modal_admin | 
driver.find_element(By.ID, "abrir_modal_admin").click()
# 31 | click | linkText=Acciones | 
driver.find_element(By.LINK_TEXT, "Acciones").click()
# 32 | click | id=sel_activo_acciones | 
driver.find_element(By.ID, "sel_activo_acciones").click()
# 33 | select | id=sel_activo_acciones | label=ACTIVO
dropdown = driver.find_element(By.ID, "sel_activo_acciones")
dropdown.find_element(By.XPATH, "//option[. = 'ACTIVO']").click()
# 34 | click | id=aplicar_filtros | 
driver.find_element(By.ID, "aplicar_filtros").click()
# 35 | click | id=cargardtaosCampanhaCompleto | 
driver.find_element(By.ID, "cargardtaosCampanhaCompleto").click()
# 36 | click | id=arcExcell | 
driver.find_element(By.ID, "arcExcell").click()
# 37 | type | id=arcExcell | C:\fakepath\cateterismo 20-12-2023.xlsx
driver.find_element(By.ID, "arcExcell").send_keys("C:\\fakepath\\cateterismo 20-12-2023.xlsx")
# 38 | click | id=cmbColumnaP | 
driver.find_element(By.ID, "cmbColumnaP").click()
# 39 | doubleClick | id=cmbColumnaP | 
element = driver.find_element(By.ID, "cmbColumnaP")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 40 | click | id=cmbColumnaP | 
driver.find_element(By.ID, "cmbColumnaP").click()
# 41 | select | id=cmbColumnaP | label=# IDENTIFICACION
dropdown = driver.find_element(By.ID, "cmbColumnaP")
dropdown.find_element(By.XPATH, "//option[. = '# IDENTIFICACION']").click()
# 42 | click | id=cheRegistrosCargarNuevo | 
driver.find_element(By.ID, "cheRegistrosCargarNuevo").click()
# 43 | doubleClick | id=cheRegistrosCargarNuevo | 
element = driver.find_element(By.ID, "cheRegistrosCargarNuevo")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 44 | click | id=cheRegistrosCargarNuevo | 
driver.find_element(By.ID, "cheRegistrosCargarNuevo").click()
# 45 | doubleClick | id=cheRegistrosCargarNuevo | 
element = driver.find_element(By.ID, "cheRegistrosCargarNuevo")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 46 | click | id=cheRegistrosCargarNuevo | 
driver.find_element(By.ID, "cheRegistrosCargarNuevo").click()
# 47 | click | id=option1 | 
driver.find_element(By.ID, "option1").click()
# 48 | click | id=selExcel1 | 
driver.find_element(By.ID, "selExcel1").click()
# 49 | select | id=selExcel1 | label=ID
dropdown = driver.find_element(By.ID, "selExcel1")
dropdown.find_element(By.XPATH, "//option[. = 'ID']").click()
# 50 | click | id=selExcel2 | 
driver.find_element(By.ID, "selExcel2").click()
# 51 | select | id=selExcel2 | label=NOMBRES
dropdown = driver.find_element(By.ID, "selExcel2")
dropdown.find_element(By.XPATH, "//option[. = 'NOMBRES']").click()
# 52 | click | id=selExcel3 | 
driver.find_element(By.ID, "selExcel3").click()
# 53 | doubleClick | id=selExcel3 | 
element = driver.find_element(By.ID, "selExcel3")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 54 | click | id=selExcel3 | 
driver.find_element(By.ID, "selExcel3").click()
# 55 | select | id=selExcel3 | label=APELLIDO 1
dropdown = driver.find_element(By.ID, "selExcel3")
dropdown.find_element(By.XPATH, "//option[. = 'APELLIDO 1']").click()
# 56 | click | id=selExcel4 | 
driver.find_element(By.ID, "selExcel4").click()
# 57 | doubleClick | id=selExcel4 | 
element = driver.find_element(By.ID, "selExcel4")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 58 | click | id=selExcel4 | 
driver.find_element(By.ID, "selExcel4").click()
# 59 | select | id=selExcel4 | label=APELLIDO 2
dropdown = driver.find_element(By.ID, "selExcel4")
dropdown.find_element(By.XPATH, "//option[. = 'APELLIDO 2']").click()
# 60 | click | id=selExcel5 | 
driver.find_element(By.ID, "selExcel5").click()
# 61 | select | id=selExcel5 | label=EPS
dropdown = driver.find_element(By.ID, "selExcel5")
dropdown.find_element(By.XPATH, "//option[. = 'EPS']").click()
# 62 | click | id=selExcel3 | 
driver.find_element(By.ID, "selExcel3").click()
# 63 | select | id=selExcel3 | label=EPS
dropdown = driver.find_element(By.ID, "selExcel3")
dropdown.find_element(By.XPATH, "//option[. = 'EPS']").click()
# 64 | click | id=selExcel3 | 
driver.find_element(By.ID, "selExcel3").click()
# 65 | select | id=selExcel3 | label=APELLIDO 1
dropdown = driver.find_element(By.ID, "selExcel3")
dropdown.find_element(By.XPATH, "//option[. = 'APELLIDO 1']").click()
# 66 | click | id=selExcel6 | 
driver.find_element(By.ID, "selExcel6").click()
# 67 | select | id=selExcel6 | label=IPS
dropdown = driver.find_element(By.ID, "selExcel6")
dropdown.find_element(By.XPATH, "//option[. = 'IPS']").click()
# 68 | click | id=selExcel7 | 
driver.find_element(By.ID, "selExcel7").click()
# 69 | select | id=selExcel7 | label=TELEFONO
dropdown = driver.find_element(By.ID, "selExcel7")
dropdown.find_element(By.XPATH, "//option[. = 'TELEFONO']").click()
# 70 | click | id=selExcel8 | 
driver.find_element(By.ID, "selExcel8").click()
# 71 | doubleClick | id=selExcel8 | 
element = driver.find_element(By.ID, "selExcel8")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 72 | click | id=selExcel8 | 
driver.find_element(By.ID, "selExcel8").click()
# 73 | doubleClick | id=selExcel8 | 
element = driver.find_element(By.ID, "selExcel8")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 74 | click | id=selExcel8 | 
driver.find_element(By.ID, "selExcel8").click()
# 75 | select | id=selExcel8 | label=CELULAR
dropdown = driver.find_element(By.ID, "selExcel8")
dropdown.find_element(By.XPATH, "//option[. = 'CELULAR']").click()
# 76 | click | id=selExcel9 | 
driver.find_element(By.ID, "selExcel9").click()
# 77 | select | id=selExcel9 | label=ESTADO
dropdown = driver.find_element(By.ID, "selExcel9")
dropdown.find_element(By.XPATH, "//option[. = 'ESTADO']").click()
# 78 | click | id=selExcel10 | 
driver.find_element(By.ID, "selExcel10").click()
# 79 | select | id=selExcel10 | label=FECHA
dropdown = driver.find_element(By.ID, "selExcel10")
dropdown.find_element(By.XPATH, "//option[. = 'FECHA']").click()
# 80 | click | id=selDB1 | 
driver.find_element(By.ID, "selDB1").click()
# 81 | select | id=selDB1 | label=ID
dropdown = driver.find_element(By.ID, "selDB1")
dropdown.find_element(By.XPATH, "//option[. = 'ID']").click()
# 82 | click | id=selDB2 | 
driver.find_element(By.ID, "selDB2").click()
# 83 | select | id=selDB2 | label=NOMBRES
dropdown = driver.find_element(By.ID, "selDB2")
dropdown.find_element(By.XPATH, "//option[. = 'NOMBRES']").click()
# 84 | click | id=selDB3 | 
driver.find_element(By.ID, "selDB3").click()
# 85 | select | id=selDB3 | label=APELLIDO 1
dropdown = driver.find_element(By.ID, "selDB3")
dropdown.find_element(By.XPATH, "//option[. = 'APELLIDO 1']").click()
# 86 | click | id=selDB4 | 
driver.find_element(By.ID, "selDB4").click()
# 87 | select | id=selDB4 | label=APELLIDO 2
dropdown = driver.find_element(By.ID, "selDB4")
dropdown.find_element(By.XPATH, "//option[. = 'APELLIDO 2']").click()
# 88 | click | id=selDB5 | 
driver.find_element(By.ID, "selDB5").click()
# 89 | select | id=selDB5 | label=EPS
dropdown = driver.find_element(By.ID, "selDB5")
dropdown.find_element(By.XPATH, "//option[. = 'EPS']").click()
# 90 | click | id=selDB6 | 
driver.find_element(By.ID, "selDB6").click()
# 91 | select | id=selDB6 | label=IPS
dropdown = driver.find_element(By.ID, "selDB6")
dropdown.find_element(By.XPATH, "//option[. = 'IPS']").click()
# 92 | click | id=selDB5 | 
driver.find_element(By.ID, "selDB5").click()
# 93 | click | id=selDB7 | 
driver.find_element(By.ID, "selDB7").click()
# 94 | doubleClick | id=selDB7 | 
element = driver.find_element(By.ID, "selDB7")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 95 | click | id=selDB7 | 
driver.find_element(By.ID, "selDB7").click()
# 96 | select | id=selDB7 | label=TELEFONO
dropdown = driver.find_element(By.ID, "selDB7")
dropdown.find_element(By.XPATH, "//option[. = 'TELEFONO']").click()
# 97 | click | id=selDB8 | 
driver.find_element(By.ID, "selDB8").click()
# 98 | select | id=selDB8 | label=CELULAR
dropdown = driver.find_element(By.ID, "selDB8")
dropdown.find_element(By.XPATH, "//option[. = 'CELULAR']").click()
# 99 | click | id=selDB9 | 
driver.find_element(By.ID, "selDB9").click()
# 100 | select | id=selDB9 | label=ESTADO
dropdown = driver.find_element(By.ID, "selDB9")
dropdown.find_element(By.XPATH, "//option[. = 'ESTADO']").click()
# 101 | click | id=selDB5 | 
driver.find_element(By.ID, "selDB5").click()
# 102 | click | id=selDB10 | 
driver.find_element(By.ID, "selDB10").click()
# 103 | select | id=selDB10 | label=FECHA INGRESO
dropdown = driver.find_element(By.ID, "selDB10")
dropdown.find_element(By.XPATH, "//option[. = 'FECHA INGRESO']").click()
# 104 | click | id=valDB7 | 
driver.find_element(By.ID, "valDB7").click()
# 105 | doubleClick | id=valDB7 | 
element = driver.find_element(By.ID, "valDB7")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 106 | click | id=valDB7 | 
driver.find_element(By.ID, "valDB7").click()
# 107 | select | id=valDB7 | label=No Validar
dropdown = driver.find_element(By.ID, "valDB7")
dropdown.find_element(By.XPATH, "//option[. = 'No Validar']").click()
# 108 | click | id=valDB8 | 
driver.find_element(By.ID, "valDB8").click()
# 109 | select | id=valDB8 | label=No Validar
dropdown = driver.find_element(By.ID, "valDB8")
dropdown.find_element(By.XPATH, "//option[. = 'No Validar']").click()
# 110 | click | css=#curpo_tabla_validaciones > tr:nth-child(10) > td:nth-child(3) | 
driver.find_element(By.CSS_SELECTOR, "#curpo_tabla_validaciones > tr:nth-child(10) > td:nth-child(3)").click()
# 111 | click | css=#btnExcell > .fa | 
driver.find_element(By.CSS_SELECTOR, "#btnExcell > .fa").click()
# 112 | click | id=cierraimportacion | 
driver.find_element(By.ID, "cierraimportacion").click()
# 113 | doubleClick | css=.blockOverlay | 
element = driver.find_element(By.CSS_SELECTOR, ".blockOverlay")
actions = ActionChains(driver)
actions.double_click(element).perform()
# 114 | click | css=.modal-lg #refrescarGrillas | 
driver.find_element(By.CSS_SELECTOR, ".modal-lg #refrescarGrillas").click()
# 115 | click | css=div:nth-child(1) > .btn-default:nth-child(2) | 
driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .btn-default:nth-child(2)").click()
