# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver

from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


driver = webdriver.Chrome()
driver.get("https://bpo-2.dyalogo.cloud/manager/login")
driver.set_window_size(1382, 736)
  
  

  

    # Test name: CP01
    # Step # | name | target | value      
    # 1 | open | https://bpo-2.dyalogo.cloud/manager/login.php | 

    # 3 | type | name=txtUsuario | santicri163@gmail.com
driver.find_element(By.NAME, "txtUsuario").send_keys("santicri163@gmail.com")
    # 4 | type | name=txtPassword | MqwoOP19
driver.find_element(By.NAME, "txtPassword").send_keys("MqwoOP190")
    # 5 | click | name=txtUsuario | 
driver.find_element(By.NAME, "txtUsuario").click()
driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()
    # 6 | type | name=txtUsuario | senadyalogo@gmail.coms
driver.find_element(By.NAME, "txtUsuario").send_keys("senadyalogo@gmail.com")
    # 7 | type | name=txtPassword | 123456789
driver.find_element(By.NAME, "txtPassword").send_keys("123456789")
    # 8 | click | css=.col-xs-4 > .btn | 
driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()
    # 9 | click | css=.select2-container--below .select2-selection__arrow | 
time.sleep(3)
try:
  driver.find_element(By.CSS_SELECTOR, ".select2-container--below .select2-selection__arrow").click()
      # 10 | click | css=.select2-search__field | 
  driver.find_element(By.CSS_SELECTOR, ".select2-search__field").click()
      # 11 | type | css=.select2-search__field | sen
  driver.find_element(By.CSS_SELECTOR, ".select2-search__field").send_keys("sena")
      # 12 | sendKeys | css=.select2-search__field | ${KEY_ENTER}
  driver.find_element(By.CSS_SELECTOR, ".select2-search__field").send_keys(Keys.ENTER)
      # 13 | click | id=btnGuardar | 
  driver.find_element(By.ID, "btnGuardar").click()
except:
 #Hace clic en el campo de huésped
    driver.find_element(By.XPATH, '//*[@id="PonerHuesped"]/div/div/form/div[2]/div/span/span[1]/span').click()
    
    # Selecciona el campo para buscar
    Huesped = driver.find_element("xpath", '/html/body/span/span/span[1]/input')
    Huesped.send_keys("SENA KIDS", Keys.ENTER)
    
    # Hace clic en el botón de guardar
    driver.find_element("xpath", '//*[@id="btnGuardar"]').click()
    
    # Espera 2 segundos
    time.sleep(2)
    # 14 | mouseOver | css=.fa-dashboard | 
driver.find_element(By.XPATH, '//*[@id="dashboard"]/a/i').click()


# 15 | mouseOut | css=.fa-dashboard | 
Option= driver.find_element(By.XPATH,'//*[@id="tiempo_real_2.0"]')
Option.click()
time.sleep(10)


driver.find_element(By.XPATH, '//*[@id="dashboard"]/a/i').click()


# 15 | mouseOut | css=.fa-dashboard | 
Option= driver.find_element(By.XPATH,'//*[@id="tiempo_real_1.0"]')
Option.click()
time.sleep(10)


driver.find_element(By.XPATH, '//*[@id="dashboard"]/a/i').click()
# 16 | mouseOver | linkText=Tiempo Real 2.0 | 
#elemendriver.find_element(By.LINK_TEXT, "Tiempo Real 2.0")
#
#actions.move_to_element(element).perform()
## 17 | mouseOver | css=.fa-dashboard | 
#elemendriver.find_element(By.CSS_SELECTOR, ".fa-dashboard")
#//*[@id="tiempo_real_2.0"]
#actions.move_to_element(element).perform()
## 18 | click | css=.fa-dashboard | 
#driver.find_element(By.CSS_SELECTOR, ".fa-dashboard").click()
## 19 | mouseOver | linkText=Tiempo Real 2.0 | 
#elemendriver.find_element(By.LINK_TEXT, "Tiempo Real 2.0")
#
#actions.move_to_element(element).perform()
## 20 | click | css=#tiempo_real_2\.0 font > font | 
#driver.find_element(By.CSS_SELECTOR, "#tiempo_real_2\\.0 font > font").click()
driver.quit()