# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCP01():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cP01(self):
    # Test name: CP01
    # Step # | name | target | value
    # 1 | open | https://bpo-2.dyalogo.cloud/manager/login.php | 
    self.driver.get("https://bpo-2.dyalogo.cloud/manager/login.php")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1382, 744)
    # 3 | click | name=txtUsuario | 
    self.driver.find_element(By.NAME, "txtUsuario").click()
    # 4 | type | name=txtUsuario | senadyalogo@gmail.co
    self.driver.find_element(By.NAME, "txtUsuario").send_keys("senadyalogo@gmail.co")
    # 5 | type | name=txtPassword | 123456789
    self.driver.find_element(By.NAME, "txtPassword").send_keys("123456789")
    # 6 | click | css=.iCheck-helper | 
    self.driver.find_element(By.CSS_SELECTOR, ".iCheck-helper").click()
    # 7 | click | css=.row:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(3)").click()
    # 8 | click | css=.col-xs-4 > .btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()
    # 9 | type | name=txtUsuario | senadyalogo@gmail.com
    self.driver.find_element(By.NAME, "txtUsuario").send_keys("senadyalogo@gmail.com")
    # 10 | type | name=txtPassword | 123456789
    self.driver.find_element(By.NAME, "txtPassword").send_keys("123456789")
    # 11 | click | id=recordarPass | 
    self.driver.find_element(By.ID, "recordarPass").click()
    # 12 | click | css=html | 
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    # 13 | doubleClick | css=html | 
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 14 | click | id=txtMail | 
    self.driver.find_element(By.ID, "txtMail").click()
    # 15 | type | id=txtMail | mesadeayuda7@dyalogo.com
    self.driver.find_element(By.ID, "txtMail").send_keys("mesadeayuda7@dyalogo.com")
    # 16 | click | id=btnEnviarPass | 
    self.driver.find_element(By.ID, "btnEnviarPass").click()
    # 17 | click | id=loginVolver | 
    self.driver.find_element(By.ID, "loginVolver").click()
    # 18 | click | css=.iCheck-helper | 
    self.driver.find_element(By.CSS_SELECTOR, ".iCheck-helper").click()
    # 19 | click | css=.col-xs-4 > .btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-xs-4 > .btn").click()
    # 20 | click | id=select2-cmbHuesped-container | 
    self.driver.find_element(By.ID, "select2-cmbHuesped-container").click()
    # 21 | type | css=.select2-search__field | SENA KIDS
    self.driver.find_element(By.CSS_SELECTOR, ".select2-search__field").send_keys("SENA KIDS")
    # 22 | sendKeys | css=.select2-search__field | ${KEY_ENTER}
    self.driver.find_element(By.CSS_SELECTOR, ".select2-search__field").send_keys(Keys.ENTER)
    # 23 | click | id=btnGuardar | 
    self.driver.find_element(By.ID, "btnGuardar").click()
  
